version: '3'
services:
  angular-ui:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4202:4202"
    container_name: angular-ui
    volumes:
       - ./:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules
